INSERT INTO DEPARTAMENTO (NOMBRE, FACULTAD, FECHACREACION, USUARIOCREACION)
SELECT n, 'FACULTAD DE INGENIERÍA ELECTRÓNICA Y TELECOMUNICACIONES', NOW(), 'seeder'
FROM (VALUES
  ('DEPARTAMENTO DE TELEMATICA '),
  ('DEPARTAMENTO DE ELECTRONICA INSTRUMENTACION Y CONTROL '),
  ('DEPARTAMENTO DE SISTEMAS'),
  ('DEPARTAMENTO DE TELECOMUNICACIONES')
) AS t(n)
ON CONFLICT (NOMBRE) DO UPDATE SET FACULTAD = EXCLUDED.FACULTAD;
