INSERT INTO DEPARTAMENTO (NOMBRE, FACULTAD, CODIGOKIRA, FECHACREACION, USUARIOCREACION)
SELECT n, 'FACULTAD DE INGENIERÍA ELECTRÓNICA Y TELECOMUNICACIONES', k, NOW(), 'seeder'
FROM (VALUES
  ('DEPARTAMENTO DE TELEMATICA ', '49'),
  ('DEPARTAMENTO DE ELECTRONICA INSTRUMENTACION Y CONTROL ', '50'),
  ('DEPARTAMENTO DE SISTEMAS', '51'),
  ('DEPARTAMENTO DE TELECOMUNICACIONES', '52')
) AS t(n, k)
ON CONFLICT (NOMBRE) DO UPDATE SET CODIGOKIRA = EXCLUDED.CODIGOKIRA;
